#!/bin/bash

cwd=inout
type=$1
input=$2
output=$3

cd /workspace
command="python ontology_viz.py -o $cwd/$input.dot -j namespace-overrides.json"

if [ "$#" -gt 3 ]; then
  shift
  shift
  shift
  export command="$command $@"
fi

export command="$command $cwd/$input"

pipenv run $command

dot -T$type -o $cwd/$output $cwd/$input.dot
